# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.12.1/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/piotrekd/workspace/cnn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/piotrekd/workspace/cnn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/piotrekd/workspace/cnn/CMakeFiles /Users/piotrekd/workspace/cnn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/piotrekd/workspace/cnn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cnn

# Build rule for target.
cnn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cnn
.PHONY : cnn

# fast build rule for target.
cnn/fast:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/build
.PHONY : cnn/fast

src/CNNLayer.o: src/CNNLayer.cpp.o
.PHONY : src/CNNLayer.o

# target to build an object file
src/CNNLayer.cpp.o:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNLayer.cpp.o
.PHONY : src/CNNLayer.cpp.o

src/CNNLayer.i: src/CNNLayer.cpp.i
.PHONY : src/CNNLayer.i

# target to preprocess a source file
src/CNNLayer.cpp.i:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNLayer.cpp.i
.PHONY : src/CNNLayer.cpp.i

src/CNNLayer.s: src/CNNLayer.cpp.s
.PHONY : src/CNNLayer.s

# target to generate assembly for a file
src/CNNLayer.cpp.s:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNLayer.cpp.s
.PHONY : src/CNNLayer.cpp.s

src/CNNLink.o: src/CNNLink.cpp.o
.PHONY : src/CNNLink.o

# target to build an object file
src/CNNLink.cpp.o:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNLink.cpp.o
.PHONY : src/CNNLink.cpp.o

src/CNNLink.i: src/CNNLink.cpp.i
.PHONY : src/CNNLink.i

# target to preprocess a source file
src/CNNLink.cpp.i:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNLink.cpp.i
.PHONY : src/CNNLink.cpp.i

src/CNNLink.s: src/CNNLink.cpp.s
.PHONY : src/CNNLink.s

# target to generate assembly for a file
src/CNNLink.cpp.s:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNLink.cpp.s
.PHONY : src/CNNLink.cpp.s

src/CNNNetwork.o: src/CNNNetwork.cpp.o
.PHONY : src/CNNNetwork.o

# target to build an object file
src/CNNNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNNetwork.cpp.o
.PHONY : src/CNNNetwork.cpp.o

src/CNNNetwork.i: src/CNNNetwork.cpp.i
.PHONY : src/CNNNetwork.i

# target to preprocess a source file
src/CNNNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNNetwork.cpp.i
.PHONY : src/CNNNetwork.cpp.i

src/CNNNetwork.s: src/CNNNetwork.cpp.s
.PHONY : src/CNNNetwork.s

# target to generate assembly for a file
src/CNNNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNNetwork.cpp.s
.PHONY : src/CNNNetwork.cpp.s

src/CNNNeuron.o: src/CNNNeuron.cpp.o
.PHONY : src/CNNNeuron.o

# target to build an object file
src/CNNNeuron.cpp.o:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNNeuron.cpp.o
.PHONY : src/CNNNeuron.cpp.o

src/CNNNeuron.i: src/CNNNeuron.cpp.i
.PHONY : src/CNNNeuron.i

# target to preprocess a source file
src/CNNNeuron.cpp.i:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNNeuron.cpp.i
.PHONY : src/CNNNeuron.cpp.i

src/CNNNeuron.s: src/CNNNeuron.cpp.s
.PHONY : src/CNNNeuron.s

# target to generate assembly for a file
src/CNNNeuron.cpp.s:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNNeuron.cpp.s
.PHONY : src/CNNNeuron.cpp.s

src/CNNWeight.o: src/CNNWeight.cpp.o
.PHONY : src/CNNWeight.o

# target to build an object file
src/CNNWeight.cpp.o:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNWeight.cpp.o
.PHONY : src/CNNWeight.cpp.o

src/CNNWeight.i: src/CNNWeight.cpp.i
.PHONY : src/CNNWeight.i

# target to preprocess a source file
src/CNNWeight.cpp.i:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNWeight.cpp.i
.PHONY : src/CNNWeight.cpp.i

src/CNNWeight.s: src/CNNWeight.cpp.s
.PHONY : src/CNNWeight.s

# target to generate assembly for a file
src/CNNWeight.cpp.s:
	$(MAKE) -f CMakeFiles/cnn.dir/build.make CMakeFiles/cnn.dir/src/CNNWeight.cpp.s
.PHONY : src/CNNWeight.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cnn"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/CNNLayer.o"
	@echo "... src/CNNLayer.i"
	@echo "... src/CNNLayer.s"
	@echo "... src/CNNLink.o"
	@echo "... src/CNNLink.i"
	@echo "... src/CNNLink.s"
	@echo "... src/CNNNetwork.o"
	@echo "... src/CNNNetwork.i"
	@echo "... src/CNNNetwork.s"
	@echo "... src/CNNNeuron.o"
	@echo "... src/CNNNeuron.i"
	@echo "... src/CNNNeuron.s"
	@echo "... src/CNNWeight.o"
	@echo "... src/CNNWeight.i"
	@echo "... src/CNNWeight.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

